### ISSUE TITLE
Posted errors when attempted to mount freedisk

### ISSUE THREAD

**Issue by anoduck** [freenet/lib-pyFreenet#7]
Recieved errors when I attempted to mount. I have compiled all the dependencies from source, and I currently run debian linux 64. I am completely lost at what could be causing it to fail. Any help would be greatly appreciated. 
My output was: 

----

"** WARNING! SSLCrypto module not installed
** Please refer to the INSTALL file within the PyFCP source package
Spawning freenetfs filesystem process...
Waiting for disk to come up...
** WARNING! SSLCrypto module not installed
** Please refer to the INSTALL file within the PyFCP source package
Creating freenetfs filesystem...
Freenetfs filesystem now alive...
Traceback (most recent call last):
  File "./freedisk", line 903, in <module>
    main()
  File "./freedisk", line 895, in main
    print mgr.run()
  File "./freedisk", line 114, in run
    result = method(*self.args[1:]) or ""
  File "./freedisk", line 255, in cmd_run
    fs.run()
  File "/home/anoduck/Sandbox/py-freenet/lib-pyFreenet/fcp/freenetfs.py", line 1675, in run
    import _fuse
ImportError: No module named _fuse
^CTraceback (most recent call last):
  File "./freedisk", line 903, in <module>
    main()
  File "./freedisk", line 895, in main
    print mgr.run()
  File "./freedisk", line 114, in run
    result = method(*self.args[1:]) or ""
  File "./freedisk", line 191, in cmd_start
    time.sleep(1)
KeyboardInterrupt"

----
:end:

**Comment by anoduck** [comment]
I found the error, and it is with the SSLCrypto not py-libfreenet. Again, great work on creating the library. It is much more feature packed than could have anticipated. Quite an accomplishment, and makes life much easier.
